/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
import java.sql.*;
import javax.swing.*;
public class Bird_watcher extends javax.swing.JFrame {
 Connection con;
 PreparedStatement pst;
    /**
     * Creates new form Bird_watcher
     */
    public Bird_watcher() {
        initComponents();
        con= SQLCON.connect();
        Connection con = null;
        Statement stmt = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblurnbirdwatcher = new javax.swing.JLabel();
        lblpasswordbirdwatcher = new javax.swing.JLabel();
        txturnbirdwatcher = new javax.swing.JTextField();
        txtPasswordbirdwatcher = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblexitbirdwatcher = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblbirdwatcherimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblurnbirdwatcher.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblurnbirdwatcher.setForeground(new java.awt.Color(204, 0, 153));
        lblurnbirdwatcher.setText("URN");
        jPanel1.add(lblurnbirdwatcher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 440, 100, -1));

        lblpasswordbirdwatcher.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblpasswordbirdwatcher.setForeground(new java.awt.Color(204, 0, 153));
        lblpasswordbirdwatcher.setText("Password");
        jPanel1.add(lblpasswordbirdwatcher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 550, 200, -1));

        txturnbirdwatcher.setBackground(new java.awt.Color(153, 204, 0));
        txturnbirdwatcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txturnbirdwatcherActionPerformed(evt);
            }
        });
        jPanel1.add(txturnbirdwatcher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 440, 290, 60));

        txtPasswordbirdwatcher.setBackground(new java.awt.Color(153, 204, 0));
        txtPasswordbirdwatcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordbirdwatcherActionPerformed(evt);
            }
        });
        jPanel1.add(txtPasswordbirdwatcher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 540, 290, 60));

        btnLogin.setBackground(new java.awt.Color(204, 0, 153));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(102, 255, 51));
        btnLogin.setText("Login");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 800, 230, 80));
        jPanel1.add(lblexitbirdwatcher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1860, 10, 30, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("x");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2320, 300, 20, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1880, 10, -1, -1));

        lblbirdwatcherimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bird Watcher Login.jpg"))); // NOI18N
        jPanel1.add(lblbirdwatcherimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 1940, 1170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 2380, 1090));

        setSize(new java.awt.Dimension(1920, 1090));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txturnbirdwatcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txturnbirdwatcherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txturnbirdwatcherActionPerformed

    private void txtPasswordbirdwatcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordbirdwatcherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordbirdwatcherActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        try{
            
            Statement stmt = con.createStatement();
            String query = "SELECT * FROM bird_watcher";
            
      
            String Username.txturnbirdwatcher.getText());
            String Password.txtPasswordbirdwatcher.getText());
        ResultSet rs =pst.executeQuery();
        if(rs.next()){
            JOptionPane.showMessageDialog(null,"Username and password matched");
            Bird_Watcher_Dash_Board dgd = new Bird_Watcher_Dash_Board();
            dgd.setVisible(true);
            setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"Incorrect NIC or password");
            txturnbirdwatcher.setText("");
            txtPasswordbirdwatcher.setText("");
        }con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bird_watcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bird_watcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bird_watcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bird_watcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bird_watcher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblbirdwatcherimage;
    private javax.swing.JLabel lblexitbirdwatcher;
    private javax.swing.JLabel lblpasswordbirdwatcher;
    private javax.swing.JLabel lblurnbirdwatcher;
    private javax.swing.JTextField txtPasswordbirdwatcher;
    private javax.swing.JTextField txturnbirdwatcher;
    // End of variables declaration//GEN-END:variables
}
