/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */

import java.sql.*;
import javax.swing.*;
public class Director_general extends javax.swing.JFrame {
 Connection con;
 PreparedStatement pst;
    /**
    /**
     * Creates new form Director_general
     */
    public Director_general() {
        initComponents();
         con= SQLCON.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblparrotdirectorgeneralloginpage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbldirectorgeneral = new javax.swing.JLabel();
        lblpassworddirectorgeneral = new javax.swing.JLabel();
        lblnicdirectorgeneral = new javax.swing.JLabel();
        txtnicdirectorgeneral = new javax.swing.JTextField();
        btnlogindirectorgeneral = new javax.swing.JButton();
        btnexistdirectorgeneral = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtdirectorgeneralpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblparrotdirectorgeneralloginpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image-removebg-preview (1).png"))); // NOI18N
        jPanel2.add(lblparrotdirectorgeneralloginpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 500, 420));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbldirectorgeneral.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbldirectorgeneral.setForeground(new java.awt.Color(0, 51, 51));
        lbldirectorgeneral.setText("Director general login");

        lblpassworddirectorgeneral.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblpassworddirectorgeneral.setText("Password:");

        lblnicdirectorgeneral.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblnicdirectorgeneral.setText("NIC:");

        txtnicdirectorgeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicdirectorgeneralActionPerformed(evt);
            }
        });

        btnlogindirectorgeneral.setText("Login");
        btnlogindirectorgeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogindirectorgeneralMouseClicked(evt);
            }
        });
        btnlogindirectorgeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogindirectorgeneralActionPerformed(evt);
            }
        });

        btnexistdirectorgeneral.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnexistdirectorgeneral.setText("x");
        btnexistdirectorgeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexistdirectorgeneralMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("x");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(601, 601, 601)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblnicdirectorgeneral)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnicdirectorgeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblpassworddirectorgeneral)
                                .addGap(18, 18, 18)
                                .addComponent(txtdirectorgeneralpassword))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(lbldirectorgeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnlogindirectorgeneral)
                        .addGap(299, 299, 299))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(btnexistdirectorgeneral)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnexistdirectorgeneral)
                    .addComponent(jLabel1))
                .addGap(83, 83, 83)
                .addComponent(lbldirectorgeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnicdirectorgeneral)
                    .addComponent(txtnicdirectorgeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpassworddirectorgeneral)
                    .addComponent(txtdirectorgeneralpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(169, 169, 169)
                .addComponent(btnlogindirectorgeneral)
                .addContainerGap(525, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 1070, 1110));

        setSize(new java.awt.Dimension(1920, 1080));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogindirectorgeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogindirectorgeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogindirectorgeneralActionPerformed

    private void btnexistdirectorgeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexistdirectorgeneralMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexistdirectorgeneralMouseClicked

    private void btnlogindirectorgeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogindirectorgeneralMouseClicked
        // TODO add your handling code here:
        try{
        String sql = "Select * from director_general where NIC=? and password=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1,txtnicdirectorgeneral.getText());
        pst.setString(2,txtdirectorgeneralpassword.getText());
        
        ResultSet rs =pst.executeQuery();
        if(rs.next()){
            JOptionPane.showMessageDialog(null,"Correct Username and password");
        Director_general_dashboard dgd = new  Director_general_dashboard ();
            dgd.setVisible(true);
            setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"Incorrect NIC or password");
            txtnicdirectorgeneral.setText("");
            txtdirectorgeneralpassword.setText("");
        }con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnlogindirectorgeneralMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtnicdirectorgeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicdirectorgeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnicdirectorgeneralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Director_general.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Director_general.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Director_general.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Director_general.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Director_general().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnexistdirectorgeneral;
    private javax.swing.JButton btnlogindirectorgeneral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbldirectorgeneral;
    private javax.swing.JLabel lblnicdirectorgeneral;
    private javax.swing.JLabel lblparrotdirectorgeneralloginpage;
    private javax.swing.JLabel lblpassworddirectorgeneral;
    private javax.swing.JPasswordField txtdirectorgeneralpassword;
    private javax.swing.JTextField txtnicdirectorgeneral;
    // End of variables declaration//GEN-END:variables
}
