/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Home_page extends javax.swing.JFrame {

    /**
     * Creates new form Home_page
     */
    public Home_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btndepartmentofficer = new javax.swing.JButton();
        btnbirdwatcher = new javax.swing.JButton();
        btndirectorgeneral = new javax.swing.JButton();
        lblexithomepage = new javax.swing.JLabel();
        lblhomeimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndepartmentofficer.setBackground(new java.awt.Color(255, 255, 255));
        btndepartmentofficer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndepartmentofficer.setForeground(new java.awt.Color(255, 153, 153));
        btndepartmentofficer.setText("Department officer");
        btndepartmentofficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepartmentofficerActionPerformed(evt);
            }
        });
        jPanel1.add(btndepartmentofficer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 870, 280, 80));

        btnbirdwatcher.setBackground(new java.awt.Color(255, 255, 255));
        btnbirdwatcher.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnbirdwatcher.setForeground(new java.awt.Color(255, 153, 153));
        btnbirdwatcher.setText("Bird watcher");
        btnbirdwatcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbirdwatcherActionPerformed(evt);
            }
        });
        jPanel1.add(btnbirdwatcher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 620, 290, 80));

        btndirectorgeneral.setBackground(new java.awt.Color(255, 255, 255));
        btndirectorgeneral.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndirectorgeneral.setForeground(new java.awt.Color(255, 153, 153));
        btndirectorgeneral.setText("Director general");
        btndirectorgeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndirectorgeneralActionPerformed(evt);
            }
        });
        jPanel1.add(btndirectorgeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 740, 290, 80));

        lblexithomepage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblexithomepage.setText("X");
        lblexithomepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblexithomepageMouseClicked(evt);
            }
        });
        jPanel1.add(lblexithomepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1890, 0, -1, -1));

        lblhomeimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home2.jpg"))); // NOI18N
        jPanel1.add(lblhomeimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2070, 1140));

        setSize(new java.awt.Dimension(1920, 1080));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblexithomepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexithomepageMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblexithomepageMouseClicked

    private void btndirectorgeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndirectorgeneralActionPerformed
        // TODO add your handling code here:

        Director_general dg= new Director_general();
        dg.show();
        this.hide();
    }//GEN-LAST:event_btndirectorgeneralActionPerformed

    private void btnbirdwatcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbirdwatcherActionPerformed
        // TODO add your handling code here:
        Bird_Watcher_Login dg= new Bird_Watcher_Login();
        dg.show();
        this.hide();
    }//GEN-LAST:event_btnbirdwatcherActionPerformed

    private void btndepartmentofficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepartmentofficerActionPerformed
        // TODO add your handling code here:
        Department_Officer dg=new Department_Officer();
        dg.show();
        this.hide();

    }//GEN-LAST:event_btndepartmentofficerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbirdwatcher;
    private javax.swing.JButton btndepartmentofficer;
    private javax.swing.JButton btndirectorgeneral;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblexithomepage;
    private javax.swing.JLabel lblhomeimage;
    // End of variables declaration//GEN-END:variables
}
